server:
  tomcat:
    max-http-header-size=81920:
  port: 8090

area: "{ 'CJDE231960054': { 'area': '三厂熔解', 'direction': '0' }, 'CJDE231960060': { 'area': '三厂熔解', 'direction': '1' }, 'CJDE231960055': { 'area': '三厂熔解', 'direction': '1' }, 'CJDE231960059': { 'area': '三厂熔解', 'direction': '0' }, 'CJDE231860985': { 'area': '四厂熔解', 'direction': '0' }, 'CJDE231860970': { 'area': '四厂熔解', 'direction': '1' }, 'CJDE231860969': { 'area': '四厂熔解', 'direction': '0' }, 'CJDE231860951': { 'area': '四厂熔解', 'direction': '1' }, 'CJDE231960052': { 'area': '一厂熔解', 'direction': '0' }, 'CJDE231860972': { 'area': '一厂熔解', 'direction': '1' }, 'CJDE231860968': { 'area': '一厂熔解', 'direction': '1' }, 'CJDE231960061': { 'area': '一厂熔解', 'direction': '0' }, 'CJDE231860955': { 'area': '三厂造型', 'direction': '0' }, 'CJDE225260588': { 'area': '三厂造型', 'direction': '1' }, 'CJDE231860974': { 'area': '三厂造型', 'direction': '0' }, 'CJDE225260707': { 'area': '三厂造型', 'direction': '1' }, 'CJDE231861051': { 'area': '四厂造型', 'direction': '0' }, 'CJDE225260697': { 'area': '四厂造型', 'direction': '1' }, 'CJDE231960057': { 'area': '四厂造型', 'direction': '0' }, 'CJDE225260584': { 'area': '四厂造型', 'direction': '1' }, 'CJDE225260587' : { 'area': '一厂造型', 'direction': '1' }, 'CJDE231860516': { 'area': '一厂造型', 'direction': '0' }, 'CJDE225260708': { 'area': '一厂造型', 'direction': '1' }, 'CJDE231960053': { 'area': '一厂造型', 'direction': '0' } }"
uploadUrl: "http://localhost:8021/api/control"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camera-ai-dbx?&serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.state.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=1000;
      filters: stat,wall,slf4j

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml # xml路径
  global-config:
    db-config:
      id-type: ASSIGN_ID # 全局默认主键策略，默认为雪花ID，若表中设置了自增，则生成的实体自动添加自增ID属性，参考 TestDelete
      logic-delete-field: deleted # 全局逻辑删除的实体字段名，若不配置，则不启用
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: false # 驼峰转下划线（默认）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志输出
  type-aliases-package: com.zkteco.attpush.entity

deviceConfig:
  deviceList:
    - SN: CJDE231960054
      area: 三厂熔解
      direction: 0


    - SN: CJDE231960060
      area: 三厂熔解
      direction: 1


    - SN: CJDE231960055
      area: 三厂熔解
      direction: 1


    - SN: CJDE231960059
      area: 三厂熔解
      direction: 0


    - SN: CJDE231860985
      area: 四厂熔解
      direction: 0


    - SN: CJDE231860970
      area: 四厂熔解
      direction: 1


    - SN: CJDE231860969
      area: 四厂熔解
      direction: 0


    - SN: CJDE231860951
      area: 四厂熔解
      direction: 1


    - SN: CJDE231960052
      area: 一厂熔解
      direction: 0


    - SN: CJDE231860972
      area: 一厂熔解
      direction: 1

    - SN: CJDE231860968
      area: 一厂熔解
      direction: 1


    - SN: CJDE231960061
      area: 一厂熔解
      direction: 0


    - SN: CJDE231860955
      area: 三厂造型
      direction: 0


    - SN: CJDE225260588
      area: 三厂造型
      direction: 1


    - SN: CJDE231860974
      area: 三厂造型
      direction: 0


    - SN: CJDE225260707
      area: 三厂造型
      direction: 1


    - SN: CJDE231861051
      area: 四厂造型
      direction: 0


    - SN: CJDE225260697
      area: 四厂造型
      direction: 1


    - SN: CJDE231960057
      area: 四厂造型
      direction: 0


    - SN: CJDE225260584
      area: 四厂造型
      direction: 1


    - SN: CJDE225260587
      area: 一厂造型
      direction: 1


    - SN: CJDE231860516
      area: 一厂造型
      direction: 0


    - SN: CJDE225260708
      area: 一厂造型
      direction: 1


    - SN: CJDE231960053
      area: 一厂造型
      direction: 0